# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "deploy"
  

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "shoorikl/keywest-search"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "keywest-search"
    working_directory: "${{clone}}"
    tag: "${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"
  
  deploy:
    stage: "deploy"
    title: K8s Deploy
    image: codefresh/cf-deploy-kubernetes:master
    commands:
      - cat /codefresh/volume/sensitive/.kube/config
      - /cf-deploy-kubernetes ./keywest-search/deployment.yml  
    environment:
      - KUBECONTEXT=k8s-demo@Google
      - KUBERNETES_NAMESPACE=my-namespace
      - MY_CUSTOM_LABEL=build-id-${{CF_BUILD_ID}} 
      - REPLICAS=1



